# This is a basic workflow to help you get started with Actions

name: dotfiles-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # test setup.sh
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Execute setup.sh
        run: ./setup.sh
        
      - name: install fish
        uses: fish-actions/install-fish@v1.1.0
      
      - name: set fisher manualy
        run: curl -sL https://git.io/fisher --create-dir -o ~/.config/fish/functions/fisher.fish
        
      - name: Test fish shell
        run: fish -c "fisher update"

  common_test:
    # test scripts correctness in .common
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: fish-actions/install-fish
        uses: fish-actions/install-fish@v1.1.0
      
      - name: fish-actions/fisher

      - name: fishtape
        uses: fish-actions/fisher@v1.0.0
        with:
          plugins: jorgebucaran/fishtape
          
      - name: test with fishtape
        run: fish -c "source .common/common.fish; and fishtape test/common_test.fish"
