# This is a basic workflow to help you get started with Actions

name: dotfiles-ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # test setup.sh
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install fish
        uses: fish-actions/install-fish@v1.1.0

      - name: Execute setup.sh
        run: ./setup.sh

      - name: Test fish shell
        run: |
          mkdir -p ~/.ssh/
          fish -c "fisher update"

      - name: install fishtape
        run: |
          fish -c "fisher install jorgebucaran/fishtape"

      - name: test with fishtape
        run: |
          fish -c "fishtape test/common_test.fish"
